# Form implementation generated from reading ui file '.\launch_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from show_three_cards_001 import DecipherThreeCards
from simple_three_cards_window_003 import Ui_Form

class Ui_MainWindow(object):
    def open_window(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()


    '''class Ui_MainWindow(object):
        def open_window(self):
            self.window = QtWidgets.QWidget()
            self.ui = DecipherThreeCards()
            self.ui.setupUi(self.window)
            self.window.show()'''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 249)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.intro_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.intro_label.setGeometry(QtCore.QRect(40, 30, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Gelo Light")
        font.setPointSize(28)
        self.intro_label.setFont(font)
        self.intro_label.setObjectName("intro_label")
        self.reading_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reading_btn.setGeometry(QtCore.QRect(40, 110, 231, 61))
        self.reading_btn.setObjectName("reading_btn")



        self.decipher_btn = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.open_window())
        self.decipher_btn.setGeometry(QtCore.QRect(310, 110, 231, 61))
        self.decipher_btn.setObjectName("decipher_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.intro_label.setText(_translate("MainWindow", "Hello! What do you want to do?"))
        self.reading_btn.setText(_translate("MainWindow", "Get a Reading"))
        self.decipher_btn.setText(_translate("MainWindow", "Decipher a Reading"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
