# Form implementation generated from reading ui file '.\win_two_meaning.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TwoSingleMeaning(object):
    def setupUi(self, TwoSingleMeaning):
        TwoSingleMeaning.setObjectName("TwoSingleMeaning")
        TwoSingleMeaning.resize(427, 508)
        self.card_01_desc = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_01_desc.setGeometry(QtCore.QRect(20, 100, 175, 140))
        self.card_01_desc.setAutoFillBackground(True)
        self.card_01_desc.setText("")
        self.card_01_desc.setWordWrap(True)
        self.card_01_desc.setObjectName("card_01_desc")
        self.card_01_title = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_01_title.setGeometry(QtCore.QRect(10, 50, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.card_01_title.setFont(font)
        self.card_01_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.card_01_title.setText("")
        self.card_01_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.card_01_title.setObjectName("card_01_title")
        self.card_02_title = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_02_title.setGeometry(QtCore.QRect(220, 50, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.card_02_title.setFont(font)
        self.card_02_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.card_02_title.setText("")
        self.card_02_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.card_02_title.setObjectName("card_02_title")
        self.card_01_neg_desc = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_01_neg_desc.setGeometry(QtCore.QRect(20, 310, 175, 140))
        self.card_01_neg_desc.setAutoFillBackground(True)
        self.card_01_neg_desc.setText("")
        self.card_01_neg_desc.setWordWrap(True)
        self.card_01_neg_desc.setObjectName("card_01_neg_desc")
        self.card_02_desc = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_02_desc.setGeometry(QtCore.QRect(230, 100, 175, 140))
        self.card_02_desc.setAutoFillBackground(True)
        self.card_02_desc.setText("")
        self.card_02_desc.setWordWrap(True)
        self.card_02_desc.setObjectName("card_02_desc")
        self.card_02_neg_desc = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.card_02_neg_desc.setGeometry(QtCore.QRect(230, 310, 175, 140))
        self.card_02_neg_desc.setAutoFillBackground(True)
        self.card_02_neg_desc.setText("")
        self.card_02_neg_desc.setWordWrap(True)
        self.card_02_neg_desc.setObjectName("card_02_neg_desc")
        self.std_label = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.std_label.setGeometry(QtCore.QRect(120, 10, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.std_label.setFont(font)
        self.std_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.std_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.std_label.setObjectName("std_label")
        self.neg_label = QtWidgets.QLabel(parent=TwoSingleMeaning)
        self.neg_label.setGeometry(QtCore.QRect(120, 250, 191, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.neg_label.setFont(font)
        self.neg_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.neg_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.neg_label.setObjectName("neg_label")

        self.retranslateUi(TwoSingleMeaning)
        QtCore.QMetaObject.connectSlotsByName(TwoSingleMeaning)

    def retranslateUi(self, TwoSingleMeaning):
        _translate = QtCore.QCoreApplication.translate
        TwoSingleMeaning.setWindowTitle(_translate("TwoSingleMeaning", "Form"))
        self.std_label.setText(_translate("TwoSingleMeaning", "Standard Meanings"))
        self.neg_label.setText(_translate("TwoSingleMeaning", "Negatives Meanings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TwoSingleMeaning = QtWidgets.QWidget()
    ui = Ui_TwoSingleMeaning()
    ui.setupUi(TwoSingleMeaning)
    TwoSingleMeaning.show()
    sys.exit(app.exec())
