# Form implementation generated from reading ui file '.\win_main_decipher_only_launch.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainLaunchWindow(object):
    def setupUi(self, MainLaunchWindow):
        MainLaunchWindow.setObjectName("MainLaunchWindow")
        MainLaunchWindow.resize(571, 244)
        self.centralwidget = QtWidgets.QWidget(parent=MainLaunchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 509, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intro_label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        self.intro_label.setFont(font)
        self.intro_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.intro_label.setObjectName("intro_label")
        self.verticalLayout.addWidget(self.intro_label)
        self.card_layout_combo = QtWidgets.QComboBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        self.card_layout_combo.setFont(font)
        self.card_layout_combo.setCurrentText("")
        self.card_layout_combo.setObjectName("card_layout_combo")
        self.verticalLayout.addWidget(self.card_layout_combo)
        self.show_cards_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        self.show_cards_btn.setFont(font)
        self.show_cards_btn.setObjectName("show_cards_btn")
        self.verticalLayout.addWidget(self.show_cards_btn)
        MainLaunchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainLaunchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 22))
        self.menubar.setObjectName("menubar")
        MainLaunchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainLaunchWindow)
        self.statusbar.setObjectName("statusbar")
        MainLaunchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainLaunchWindow)
        QtCore.QMetaObject.connectSlotsByName(MainLaunchWindow)

    def retranslateUi(self, MainLaunchWindow):
        _translate = QtCore.QCoreApplication.translate
        MainLaunchWindow.setWindowTitle(_translate("MainLaunchWindow", "MainWindow"))
        self.intro_label.setText(_translate("MainLaunchWindow", "Please select your tarot spread:"))
        self.show_cards_btn.setText(_translate("MainLaunchWindow", "Show Me The Cards"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainLaunchWindow = QtWidgets.QMainWindow()
    ui = Ui_MainLaunchWindow()
    ui.setupUi(MainLaunchWindow)
    MainLaunchWindow.show()
    sys.exit(app.exec())
