from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThreeExplainPopup(object):
    def setupUi(self, ThreeDecipher):
        ThreeDecipher.setObjectName("ThreeDecipher")
        ThreeDecipher.resize(674, 502)
        self.pas_label = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pas_label.setGeometry(QtCore.QRect(30, 20, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pas_label.setFont(font)
        self.pas_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pas_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pas_label.setObjectName("pas_label")
        self.pre_label = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pre_label.setGeometry(QtCore.QRect(240, 20, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pre_label.setFont(font)
        self.pre_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pre_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pre_label.setObjectName("pre_label")
        self.fut_label = QtWidgets.QLabel(parent=ThreeDecipher)
        self.fut_label.setGeometry(QtCore.QRect(450, 20, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.fut_label.setFont(font)
        self.fut_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fut_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fut_label.setObjectName("fut_label")
        self.pas_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pas_desc.setGeometry(QtCore.QRect(40, 110, 175, 140))
        self.pas_desc.setAutoFillBackground(True)
        self.pas_desc.setText("")
        self.pas_desc.setWordWrap(True)
        self.pas_desc.setObjectName("pas_desc")
        self.pre_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pre_desc.setGeometry(QtCore.QRect(250, 110, 175, 140))
        self.pre_desc.setAutoFillBackground(True)
        self.pre_desc.setText("")
        self.pre_desc.setWordWrap(True)
        self.pre_desc.setObjectName("pre_desc")
        self.fut_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.fut_desc.setGeometry(QtCore.QRect(460, 110, 175, 140))
        self.fut_desc.setAutoFillBackground(True)
        self.fut_desc.setText("")
        self.fut_desc.setWordWrap(True)
        self.fut_desc.setObjectName("fut_desc")
        self.pre_card_title = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pre_card_title.setGeometry(QtCore.QRect(240, 60, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pre_card_title.setFont(font)
        self.pre_card_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pre_card_title.setText("")
        self.pre_card_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pre_card_title.setObjectName("pre_card_title")
        self.pas_card_title = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pas_card_title.setGeometry(QtCore.QRect(30, 60, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pas_card_title.setFont(font)
        self.pas_card_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pas_card_title.setText("")
        self.pas_card_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pas_card_title.setObjectName("pas_card_title")
        self.fut_card_title = QtWidgets.QLabel(parent=ThreeDecipher)
        self.fut_card_title.setGeometry(QtCore.QRect(450, 60, 195, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.fut_card_title.setFont(font)
        self.fut_card_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fut_card_title.setText("")
        self.fut_card_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fut_card_title.setObjectName("fut_card_title")
        self.pas_neg_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pas_neg_desc.setGeometry(QtCore.QRect(40, 320, 175, 140))
        self.pas_neg_desc.setAutoFillBackground(True)
        self.pas_neg_desc.setText("")
        self.pas_neg_desc.setWordWrap(True)
        self.pas_neg_desc.setObjectName("pas_neg_desc")
        self.pre_neg_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pre_neg_desc.setGeometry(QtCore.QRect(250, 320, 175, 140))
        self.pre_neg_desc.setAutoFillBackground(True)
        self.pre_neg_desc.setText("")
        self.pre_neg_desc.setWordWrap(True)
        self.pre_neg_desc.setObjectName("pre_neg_desc")
        self.fut_neg_desc = QtWidgets.QLabel(parent=ThreeDecipher)
        self.fut_neg_desc.setGeometry(QtCore.QRect(460, 320, 175, 140))
        self.fut_neg_desc.setAutoFillBackground(True)
        self.fut_neg_desc.setText("")
        self.fut_neg_desc.setWordWrap(True)
        self.fut_neg_desc.setObjectName("fut_neg_desc")
        self.pas_neg = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pas_neg.setGeometry(QtCore.QRect(30, 260, 191, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pas_neg.setFont(font)
        self.pas_neg.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pas_neg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pas_neg.setObjectName("pas_neg")
        self.pre_neg = QtWidgets.QLabel(parent=ThreeDecipher)
        self.pre_neg.setGeometry(QtCore.QRect(240, 260, 191, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.pre_neg.setFont(font)
        self.pre_neg.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pre_neg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pre_neg.setObjectName("pre_neg")
        self.fut_neg = QtWidgets.QLabel(parent=ThreeDecipher)
        self.fut_neg.setGeometry(QtCore.QRect(450, 260, 191, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.fut_neg.setFont(font)
        self.fut_neg.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fut_neg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fut_neg.setObjectName("fut_neg")

        self.retranslateUi(ThreeDecipher)
        QtCore.QMetaObject.connectSlotsByName(ThreeDecipher)

    def retranslateUi(self, ThreeDecipher):
        _translate = QtCore.QCoreApplication.translate
        ThreeDecipher.setWindowTitle(_translate("ThreeDecipher", "Form"))
        self.pas_label.setText(_translate("ThreeDecipher", "Past"))
        self.pre_label.setText(_translate("ThreeDecipher", "Present"))
        self.fut_label.setText(_translate("ThreeDecipher", "Future"))
        self.pas_neg.setText(_translate("ThreeDecipher", "Negatives"))
        self.pre_neg.setText(_translate("ThreeDecipher", "Negatives"))
        self.fut_neg.setText(_translate("ThreeDecipher", "Negatives"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThreeDecipher = QtWidgets.QWidget()
    ui = Ui_ThreeExplainPopup()
    ui.setupUi(ThreeDecipher)
    ThreeDecipher.show()
    sys.exit(app.exec())
