# Form implementation generated from reading ui file '.\read_in_one_card_001.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(244, 346)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(20, 10, 201, 311))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.card_01 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_01.setFont(font)
        self.card_01.setObjectName("card_01")
        self.gridLayout.addWidget(self.card_01, 0, 0, 1, 2)
        self.card_01_arcana = QtWidgets.QLabel(parent=self.widget)
        self.card_01_arcana.setObjectName("card_01_arcana")
        self.gridLayout.addWidget(self.card_01_arcana, 1, 0, 1, 1)
        self.card_01_major = QtWidgets.QRadioButton(parent=self.widget)
        self.card_01_major.setObjectName("card_01_major")
        self.gridLayout.addWidget(self.card_01_major, 1, 1, 1, 1)
        self.card_01_minor = QtWidgets.QRadioButton(parent=self.widget)
        self.card_01_minor.setObjectName("card_01_minor")
        self.gridLayout.addWidget(self.card_01_minor, 2, 1, 1, 1)
        self.card_01_number_spin = QtWidgets.QSpinBox(parent=self.widget)
        self.card_01_number_spin.setObjectName("card_01_number_spin")
        self.gridLayout.addWidget(self.card_01_number_spin, 3, 0, 1, 1)
        self.card_01_suits = QtWidgets.QComboBox(parent=self.widget)
        self.card_01_suits.setObjectName("card_01_suits")
        self.gridLayout.addWidget(self.card_01_suits, 3, 1, 1, 1)
        self.card_01_major_combo = QtWidgets.QComboBox(parent=self.widget)
        self.card_01_major_combo.setObjectName("card_01_major_combo")
        self.gridLayout.addWidget(self.card_01_major_combo, 4, 0, 1, 2)
        self.card_01_mean_btn = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.card_01_mean_btn.setFont(font)
        self.card_01_mean_btn.setObjectName("card_01_mean_btn")
        self.gridLayout.addWidget(self.card_01_mean_btn, 5, 0, 1, 2)
        self.card_01_mean_label = QtWidgets.QLabel(parent=self.widget)
        self.card_01_mean_label.setText("")
        self.card_01_mean_label.setObjectName("card_01_mean_label")
        self.gridLayout.addWidget(self.card_01_mean_label, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.card_01.setText(_translate("Form", "First Card"))
        self.card_01_arcana.setText(_translate("Form", "Arcana"))
        self.card_01_major.setText(_translate("Form", "Major"))
        self.card_01_minor.setText(_translate("Form", "Minor"))
        self.card_01_mean_btn.setText(_translate("Form", "Get Meaning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
