# Form implementation generated from reading ui file '.\show_three_cards_001.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 523)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(40, 40, 651, 441))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pas_img_label = QtWidgets.QLabel(parent=self.widget)
        self.pas_img_label.setText("")
        self.pas_img_label.setScaledContents(False)
        self.pas_img_label.setObjectName("pas_img_label")
        self.gridLayout.addWidget(self.pas_img_label, 0, 0, 1, 1)
        self.pre_img_label = QtWidgets.QLabel(parent=self.widget)
        self.pre_img_label.setText("")
        self.pre_img_label.setObjectName("pre_img_label")
        self.gridLayout.addWidget(self.pre_img_label, 0, 1, 1, 1)
        self.fut_img_label = QtWidgets.QLabel(parent=self.widget)
        self.fut_img_label.setText("")
        self.fut_img_label.setObjectName("fut_img_label")
        self.gridLayout.addWidget(self.fut_img_label, 0, 2, 1, 1)
        self.pas_combo = QtWidgets.QComboBox(parent=self.widget)
        self.pas_combo.setObjectName("pas_combo")
        self.gridLayout.addWidget(self.pas_combo, 1, 0, 1, 1)
        self.pre_combo = QtWidgets.QComboBox(parent=self.widget)
        self.pre_combo.setObjectName("pre_combo")
        self.gridLayout.addWidget(self.pre_combo, 1, 1, 1, 1)
        self.fut_combo = QtWidgets.QComboBox(parent=self.widget)
        self.fut_combo.setObjectName("fut_combo")
        self.gridLayout.addWidget(self.fut_combo, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
