# Form implementation generated from reading ui file '.\win_single_deci.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(345, 550)
        self.single_img_label = QtWidgets.QLabel(parent=Form)
        self.single_img_label.setGeometry(QtCore.QRect(90, 40, 175, 315))
        self.single_img_label.setText("")
        self.single_img_label.setObjectName("single_img_label")
        self.single_card_combo = QtWidgets.QComboBox(parent=Form)
        self.single_card_combo.setGeometry(QtCore.QRect(90, 430, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(20)
        self.single_card_combo.setFont(font)
        self.single_card_combo.setObjectName("single_card_combo")
        self.decipher_btn = QtWidgets.QPushButton(parent=Form)
        self.decipher_btn.setGeometry(QtCore.QRect(50, 480, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(16)
        self.decipher_btn.setFont(font)
        self.decipher_btn.setObjectName("decipher_btn")
        self.select_card_label = QtWidgets.QLabel(parent=Form)
        self.select_card_label.setGeometry(QtCore.QRect(120, 390, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(16)
        self.select_card_label.setFont(font)
        self.select_card_label.setObjectName("select_card_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.decipher_btn.setText(_translate("Form", "Decipher Card"))
        self.select_card_label.setText(_translate("Form", "Select Card:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
