# Form implementation generated from reading ui file '.\win_single_read_02.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UiSingleReading(object):
    def setupUi(self, UiSingleReading):
        UiSingleReading.setObjectName("UiSingleReading")
        UiSingleReading.resize(340, 485)
        self.decipher_btn = QtWidgets.QPushButton(parent=UiSingleReading)
        self.decipher_btn.setGeometry(QtCore.QRect(70, 430, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.decipher_btn.setFont(font)
        self.decipher_btn.setObjectName("decipher_btn")
        self.card_img = QtWidgets.QLabel(parent=UiSingleReading)
        self.card_img.setGeometry(QtCore.QRect(80, 30, 175, 315))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.card_img.setFont(font)
        self.card_img.setAutoFillBackground(True)
        self.card_img.setText("")
        self.card_img.setObjectName("card_img")
        self.draw_btn = QtWidgets.QPushButton(parent=UiSingleReading)
        self.draw_btn.setGeometry(QtCore.QRect(30, 380, 280, 26))
        font = QtGui.QFont()
        font.setFamily("Cormorant Infant SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.draw_btn.setFont(font)
        self.draw_btn.setObjectName("draw_btn")

        self.retranslateUi(UiSingleReading)
        QtCore.QMetaObject.connectSlotsByName(UiSingleReading)

    def retranslateUi(self, UiSingleReading):
        _translate = QtCore.QCoreApplication.translate
        UiSingleReading.setWindowTitle(_translate("UiSingleReading", "Form"))
        self.decipher_btn.setText(_translate("UiSingleReading", "Show Explanation"))
        self.draw_btn.setText(_translate("UiSingleReading", "Draw Card"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiSingleReading = QtWidgets.QWidget()
    ui = Ui_UiSingleReading()
    ui.setupUi(UiSingleReading)
    UiSingleReading.show()
    sys.exit(app.exec())
