# Form implementation generated from reading ui file '.\win_three_deci.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UiThreeDecipher(object):
    def setupUi(self, UiThreeDecipher):
        UiThreeDecipher.setObjectName("UiThreeDecipher")
        UiThreeDecipher.resize(707, 559)
        self.pas_img = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.pas_img.setGeometry(QtCore.QRect(60, 90, 175, 315))
        self.pas_img.setAutoFillBackground(True)
        self.pas_img.setText("")
        self.pas_img.setObjectName("pas_img")
        self.pre_img = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.pre_img.setGeometry(QtCore.QRect(270, 90, 175, 315))
        self.pre_img.setAutoFillBackground(True)
        self.pre_img.setText("")
        self.pre_img.setObjectName("pre_img")
        self.fut_img = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.fut_img.setGeometry(QtCore.QRect(480, 90, 175, 315))
        self.fut_img.setAutoFillBackground(True)
        self.fut_img.setText("")
        self.fut_img.setObjectName("fut_img")
        self.pas_combo = QtWidgets.QComboBox(parent=UiThreeDecipher)
        self.pas_combo.setGeometry(QtCore.QRect(60, 460, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(20)
        self.pas_combo.setFont(font)
        self.pas_combo.setObjectName("pas_combo")
        self.pre_combo = QtWidgets.QComboBox(parent=UiThreeDecipher)
        self.pre_combo.setGeometry(QtCore.QRect(270, 460, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(20)
        self.pre_combo.setFont(font)
        self.pre_combo.setObjectName("pre_combo")
        self.fut_combo = QtWidgets.QComboBox(parent=UiThreeDecipher)
        self.fut_combo.setGeometry(QtCore.QRect(480, 460, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(20)
        self.fut_combo.setFont(font)
        self.fut_combo.setObjectName("fut_combo")
        self.pas_label = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.pas_label.setGeometry(QtCore.QRect(130, 40, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.pas_label.setFont(font)
        self.pas_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pas_label.setObjectName("pas_label")
        self.pres_label = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.pres_label.setGeometry(QtCore.QRect(320, 40, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.pres_label.setFont(font)
        self.pres_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pres_label.setObjectName("pres_label")
        self.fut_label = QtWidgets.QLabel(parent=UiThreeDecipher)
        self.fut_label.setGeometry(QtCore.QRect(530, 40, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.fut_label.setFont(font)
        self.fut_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fut_label.setObjectName("fut_label")
        self.decipher_btn = QtWidgets.QPushButton(parent=UiThreeDecipher)
        self.decipher_btn.setGeometry(QtCore.QRect(179, 510, 361, 35))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(16)
        self.decipher_btn.setFont(font)
        self.decipher_btn.setObjectName("decipher_btn")

        self.retranslateUi(UiThreeDecipher)
        QtCore.QMetaObject.connectSlotsByName(UiThreeDecipher)

    def retranslateUi(self, UiThreeDecipher):
        _translate = QtCore.QCoreApplication.translate
        UiThreeDecipher.setWindowTitle(_translate("UiThreeDecipher", "Form"))
        self.pas_label.setText(_translate("UiThreeDecipher", "Past"))
        self.pres_label.setText(_translate("UiThreeDecipher", "Present"))
        self.fut_label.setText(_translate("UiThreeDecipher", "Future"))
        self.decipher_btn.setText(_translate("UiThreeDecipher", "Decipher Cards"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiThreeDecipher = QtWidgets.QWidget()
    ui = Ui_UiThreeDecipher()
    ui.setupUi(UiThreeDecipher)
    UiThreeDecipher.show()
    sys.exit(app.exec())
