# Form implementation generated from reading ui file '.\win_three_read.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UiThreeReading(object):
    def setupUi(self, UiThreeReading):
        UiThreeReading.setObjectName("UiThreeReading")
        UiThreeReading.resize(699, 558)
        self.pre_img = QtWidgets.QLabel(parent=UiThreeReading)
        self.pre_img.setGeometry(QtCore.QRect(261, 80, 175, 315))
        self.pre_img.setAutoFillBackground(True)
        self.pre_img.setText("")
        self.pre_img.setObjectName("pre_img")
        self.pas_img = QtWidgets.QLabel(parent=UiThreeReading)
        self.pas_img.setGeometry(QtCore.QRect(51, 80, 175, 315))
        self.pas_img.setAutoFillBackground(True)
        self.pas_img.setText("")
        self.pas_img.setObjectName("pas_img")
        self.pas_label = QtWidgets.QLabel(parent=UiThreeReading)
        self.pas_label.setGeometry(QtCore.QRect(121, 30, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.pas_label.setFont(font)
        self.pas_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pas_label.setObjectName("pas_label")
        self.pre_label = QtWidgets.QLabel(parent=UiThreeReading)
        self.pre_label.setGeometry(QtCore.QRect(311, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.pre_label.setFont(font)
        self.pre_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pre_label.setObjectName("pre_label")
        self.fut_label = QtWidgets.QLabel(parent=UiThreeReading)
        self.fut_label.setGeometry(QtCore.QRect(521, 30, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(18)
        self.fut_label.setFont(font)
        self.fut_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fut_label.setObjectName("fut_label")
        self.fut_img = QtWidgets.QLabel(parent=UiThreeReading)
        self.fut_img.setGeometry(QtCore.QRect(471, 80, 175, 315))
        self.fut_img.setAutoFillBackground(True)
        self.fut_img.setText("")
        self.fut_img.setObjectName("fut_img")
        self.decipher_btn = QtWidgets.QPushButton(parent=UiThreeReading)
        self.decipher_btn.setGeometry(QtCore.QRect(170, 500, 361, 35))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(16)
        self.decipher_btn.setFont(font)
        self.decipher_btn.setObjectName("decipher_btn")
        self.pas_btn = QtWidgets.QPushButton(parent=UiThreeReading)
        self.pas_btn.setGeometry(QtCore.QRect(50, 440, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(12)
        self.pas_btn.setFont(font)
        self.pas_btn.setObjectName("pas_btn")
        self.pre_btn = QtWidgets.QPushButton(parent=UiThreeReading)
        self.pre_btn.setGeometry(QtCore.QRect(260, 440, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(12)
        font.setBold(False)
        self.pre_btn.setFont(font)
        self.pre_btn.setObjectName("pre_btn")
        self.fut_btn = QtWidgets.QPushButton(parent=UiThreeReading)
        self.fut_btn.setGeometry(QtCore.QRect(470, 440, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Hebrew")
        font.setPointSize(12)
        self.fut_btn.setFont(font)
        self.fut_btn.setObjectName("fut_btn")

        self.retranslateUi(UiThreeReading)
        QtCore.QMetaObject.connectSlotsByName(UiThreeReading)

    def retranslateUi(self, UiThreeReading):
        _translate = QtCore.QCoreApplication.translate
        UiThreeReading.setWindowTitle(_translate("UiThreeReading", "Form"))
        self.pas_label.setText(_translate("UiThreeReading", "Past"))
        self.pre_label.setText(_translate("UiThreeReading", "Present"))
        self.fut_label.setText(_translate("UiThreeReading", "Future"))
        self.decipher_btn.setText(_translate("UiThreeReading", "Read My Cards!"))
        self.pas_btn.setText(_translate("UiThreeReading", "Draw Card"))
        self.pre_btn.setText(_translate("UiThreeReading", "Draw Card"))
        self.fut_btn.setText(_translate("UiThreeReading", "Draw Card"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiThreeReading = QtWidgets.QWidget()
    ui = Ui_UiThreeReading()
    ui.setupUi(UiThreeReading)
    UiThreeReading.show()
    sys.exit(app.exec())
