minor_full_dict = {'Ace of Wands': 'spark of potential growth',
                   'Two of Wands': 'First fruits of labor',
                   'Three of Wands': 'Burst into the world',
                   'Four of Wands': 'Sexual and creative stability which risks boredom and routine',
                   'Five of Wands': 'Temptation to push for more, pull at the veil',
                   'Six of Wands': 'Ready to move outward, to go from solo to paired',
                   'Seven of Wands': 'Action in creation, tangible engagement',
                   'Eight of Wands': 'Scattered to focused, full concentration',
                   'Nine of Wands': 'Make no concessions, be yourself, be responsible but win or die',
                   'Ten of Wands': 'Energy graduated, moving on to the next level, painful relinquishment of energy',
                   'Page of Wands': '',
                   'Queen of Wands': '',
                   'King of Wands': '',
                   'Knight of Wands': '',
                   'Ace of Coins': 'Growth of money',
                   'Two of Coins': 'Spiritualization of matter, work made tangible',
                   'Three of Coins': 'First results, fertility issues',
                   'Four of Coins': 'Must commit to action or lose progress, spend',
                   'Five of Coins': 'New possibility of wealth, spend wisely',
                   'Six of Coins': 'Balance of conflicting values, harmony in all aspects of life',
                   'Seven of Coins': 'Realizing of ideas, make your ideal',
                   'Eight of Coins': 'True wealth in all life, thorough understanding',
                   'Nine of Coins': 'Arrival of new material conditions, baby, new job, stroke of fortune, '
                                     'birth of a new dimension',
                   'Ten of Coins': 'All has been attained in the material plane',
                   'Page of Coins': '',
                   'Queen of Coins': '',
                   'King of Coins': '',
                   'Knight of Coins': '',
                   'Ace of Swords': 'A flash of insight, guidance to simplify the mind, cut the unnecessary',
                   'Two of Swords': 'Daydreams, plans, information, theories overflowing',
                   'Three of Swords': 'Discern between belief and knowing, too excitable, enthusiasm in learning',
                   'Four of Swords': 'Good at life in general, practical but shuts out matters of the heart',
                   'Five of Swords': 'False understanding of the world, dangerous polarizing, too enthusiastic',
                   'Six of Swords': 'Attain beauty from within, meditate',
                   'Seven of Swords': 'Lessons in receptivity, remove distractions',
                   'Eight of Swords': 'Emptiness, the buddhist void',
                   'Nine of Swords': 'Listen to others, there are other ideas than your own',
                   'Ten of Swords': 'The mind has achieved unity, a full understanding',
                   'Page of Swords': '',
                   'Queen of Swords': '',
                   'King of Swords': '',
                   'Knight of Swords': '',
                   'Ace of Cups': 'A gift of love given freely',
                   'Two of Cups': 'Combining of opposite forces, love is blind',
                   'Three of Cups': 'Divine love, honeymoon feelings',
                   'Four of Cups': 'Seeking outer validation, insecure in love',
                   'Five of Cups': 'Misunderstanding of love, cult like love',
                   'Six of Cups': 'soul mates, potential narcissism, love reflecting what it sees, not honest',
                   'Seven of Cups': 'Full manifestation of love',
                   'Eight of Cups': 'Active towards earth receptive towards the heavens, perfect balance, perfect '
                                     'love, a full cup',
                   'Nine of Cups': 'Release emotions which used to nourish, analyze your love',
                   'Ten of Cups': 'Nothing for me that is not for others, full heart',
                   'Page of Cups': '',
                   'Queen of Cups': '',
                   'King of Cups': '',
                   'Knight of Cups': ''
                   }