modality_dict = {'Wands': 'Active',
                 'Swords': 'Active',
                 'Pentacles': 'Receptive',
                 'Cups': 'Receptive',
                 'Fool': 'Active',
                 'Magician': 'Active',
                 'High Priestess': 'Receptive',
                 'Empress': 'Receptive',
                 'Emperor': 'Active',
                 'Hierophant': 'Receptive',
                 'Lovers': 'Active',
                 'Chariot': 'Receptive',
                 'Strength': 'Active',
                 'Hermit': 'Receptive',
                 'Wheel of Fortune': 'Receptive',
                 'Justice': 'Active',
                 'Hanged Man': 'Receptive',
                 'Death': 'Receptive',
                 'Temperance': 'Active',
                 'Devil': 'Receptive',
                 'Tower': 'Receptive',
                 'Star': 'Active',
                 'Moon': 'Receptive',
                 'Sun': 'Active',
                 'Judgement': 'Receptive',
                 'World': 'Active'
                 }