# Form implementation generated from reading ui file '.\win_main_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from win_card_module import Ui_CardModule

number_list = ["1", "2", "3"]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 669)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 69, 751, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.SpreadCardLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SpreadCardLayout.setContentsMargins(0, 0, 0, 0)
        self.SpreadCardLayout.setObjectName("SpreadCardLayout")

        self.read_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.read_btn.setGeometry(QtCore.QRect(280, 550, 241, 24))
        self.read_btn.setObjectName("read_btn")

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 20, 561, 24))
        self.widget.setObjectName("widget")

        self.SpreadDetailsLayout = QtWidgets.QHBoxLayout(self.widget)
        self.SpreadDetailsLayout.setContentsMargins(0, 0, 0, 0)
        self.SpreadDetailsLayout.setObjectName("SpreadDetailsLayout")

        self.spread_combo = QtWidgets.QComboBox(parent=self.widget)
        self.spread_combo.setObjectName("spread_combo")
        self.spread_combo.addItems(number_list)

        self.SpreadDetailsLayout.addWidget(self.spread_combo)

        self.cat_combo = QtWidgets.QComboBox(parent=self.widget)
        self.cat_combo.setObjectName("cat_combo")
        self.SpreadDetailsLayout.addWidget(self.cat_combo)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.card_info = QtWidgets.QWidget()
        self.ui = Ui_CardModule()
        self.ui.setupUi(self.card_info)
        self.ui.card_title.setText("ITS HERE!")

        self.card_info2 = QtWidgets.QWidget()
        self.ui2 = Ui_CardModule()
        self.ui2.setupUi(self.card_info2)
        self.ui2.card_title.setText("ITS THERE!")

        self.card_info2.setGeometry(500, 300, 254, 469)

        # self.SpreadCardLayout.addWidget(self.add_card)
        self.SpreadCardLayout.addWidget(self.card_info)
        self.SpreadCardLayout.addWidget(self.card_info2)

        # self.SpreadCardLayout.addLayout()

    # def add_card(self):
    #     self.card_info = QtWidgets.QWidget()
    #     self.ui = Ui_CardModule()
    #     self.ui.setupUi(self.card_info)
    #     self.ui.card_title.setText("ITS HERE!")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.read_btn.setText(_translate("MainWindow", "Read Cards"))
        # maybe here is where i should add the module card


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
